Adds i18n to the site
purefinance/pure.finance pull request #22
Opened 2021-04-07 15:09 UTC by mbonfoster

This PR adds i18n to the site, but depends on using a server since next export doesn't support i18n.
To merge this PR we need to change our current setup, start using a server and stop exporting the site as static.
We should also integrate this repository with transifex.
Closes #16

2021-04-07 15:26 UTC, raiseerco submitted a review, later dismissed

2021-04-22 20:20 UTC, raiseerco approved these changes

2021-04-22 20:31 UTC, gabmontes requested changes
Only minor comments. In general looks very good!!

2021-04-22 20:31 UTC, gabmontes commented on .travis.yml
> +  - '12' # AWS default
Let's start use Node 14 and match the `Dockerfile`.

2021-04-22 20:31 UTC, gabmontes commented on .travis.yml
> +  submodules: false
This is not required and can be removed.

2021-04-22 20:31 UTC, gabmontes commented on scripts/1-site
> +# if [ -n "$(echo "$CHANGED" | { grep pure-site || true; })" ]; then
This line (and closing line at the end) should be enabled. Correct?

2021-04-22 20:31 UTC, gabmontes commented on scripts/1-site
> +echo "APP WEB SERVER"
Could be simplified to just "WEB SERVER" here and below.

2021-04-22 20:46 UTC, gabmontes approved these changes

2021-04-22 20:48 UTC, raiseerco approved these changes

2021-04-22 21:43 UTC, merged